/**
 * This file was automatically generated by tools/generators/generate-cache-file.js file
 */


import { productsApi } from "./products-endpoints"

  export const addProductsCacheKeys = () =>
  productsApi.enhanceEndpoints({
    endpoints: {
      getManyProducts: { providesTags: ["products"] },
      createOneProduct: { invalidatesTags: ["products"] },
      updateOneProduct: { invalidatesTags: ["products"] },
      deleteOneProduct: { invalidatesTags: ["products"] },
    },
  })
  
export const addGeneratedCacheKeys = () => {

  addProductsCacheKeys()
}
