version: "3.6"
services:
  database:
    image: postgres:13
    container_name: ventionsubmission-postgres
    ports:
      - 5433:5432
    restart: always
    command:
      - postgres
      - -c
      - listen_addresses=*
    environment:
      POSTGRES_DB: ventionsubmission
      POSTGRES_HOST_AUTH_METHOD: "trust" # Not recommended, only for demo purposes
    volumes:
      # seeding
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      # named volume
      - ventionsubmission-data:/var/lib/postgresql/ventionsubmission/data

volumes:
  ventionsubmission-data:
